/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/catalog': RouteRecordInfo<'/catalog', '/catalog', Record<never, never>, Record<never, never>>,
    '/core': RouteRecordInfo<'/core', '/core', Record<never, never>, Record<never, never>>,
    '/core/': RouteRecordInfo<'/core/', '/core', Record<never, never>, Record<never, never>>,
    '/core/autoSkeletonScreen': RouteRecordInfo<'/core/autoSkeletonScreen', '/core/autoSkeletonScreen', Record<never, never>, Record<never, never>>,
    '/core/autoUtils': RouteRecordInfo<'/core/autoUtils', '/core/autoUtils', Record<never, never>, Record<never, never>>,
    '/core/createAsyncQueue': RouteRecordInfo<'/core/createAsyncQueue', '/core/createAsyncQueue', Record<never, never>, Record<never, never>>,
    '/core/createCancelableTask': RouteRecordInfo<'/core/createCancelableTask', '/core/createCancelableTask', Record<never, never>, Record<never, never>>,
    '/core/useAutoRefresh': RouteRecordInfo<'/core/useAutoRefresh', '/core/useAutoRefresh', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
